fn do_sth_that_might_fail(i:i32) -> Result<f32,String> {
    if i == 42 {
	Ok(13.0)
    } else {
	Err(String::from("this is not the right number"))
    }
}

fn main() {
    let result = do_sth_that_might_fail(12);

    match result {
	Ok(c) => println!("found {}", v);
	Err
    }
}
